### PR TITLE
Reorganization

### PR DESCRIPTION
**Pull request by ginafish**
Some minor edits, but on the whole just reorganized/renamed the folders.
Major changes:

- Made the Readme more... more.

- Renamed folders to attribute authors
    - Reason - multiple people might want to use the same name for their themes, ex: "Dark TD". 

- Removed the for- in front of the main folder names
    - Reason - 1. It bugged me 2. Unnecessarily bloats the folder names imo.

- Renamed "packages" to "Compilations"
    - Reason - we have non-CS majors working in our department who may not be familiar with programming jargon, so "Packages" isn't something that they may necessarily recognize, while "Compilations" would probably be more recognizable.

### CODE REVIEW

**Comment by cascadeth** [comment]
Alrighty, here's m' notes: 

## DIRECTORIES: 

### For
Removing the `for-` is cool.  Just what I had for initial.  Makes sense to get everything consolidated.  

### Structure
Want to confirm directory structure with you: 
`for_what_site/author/style_name/(style files here)`
E.g. `TeamDynamix/styles/cascadeth/TDWarm/(all style files)`

### Packages
As far as the packages dir, I think it's fairly self explanatory.  Package nomenclature is used elsewhere in the IT world, where most of our techs have heard it a few times.  It's a installer of multiple things in one wrap/package( like the Office 2016 package installs Word, Excel, PowerP, etc. ).  We can add to the main readme about this dir, explaining: If you want multiple styles installed at the same time, look here, and "do this".  "do this" leads to the next thought...

### Readme Installation Section
Since installing the styles can only happen in one of a few ways, since we're using Stylish to apply them, I'm guessing a section in the main readme could explain how to install the style(s) depending upon the type:

- Package(JSON format): Stylish's retrieve backup option.  Auto-installs every style included in the package.
- Per style(MOZILLA format): Stylish's import/export option.  Auto installs one complete style (even if there are multiple sections)
- Section of style(CSS format): Create new style, add plaintext CSS, and save.  

***
## FILES:
Keeping file content low, remove(if you can) all the files appended with ~master or ~HEAD.  Really we only want the source files, and not extraneous copies... I can remove these later if needed, but we really all should be on the same repository format.  Idk where those came from...

**Comment by cascadeth** [comment]
O and maybe a contact readme in each person's named directories

**Comment by ginafish** [comment]
### Structure
Oh switching to username/style from username-style name isn't a bad idea.  I don't know how I exactly feel about it though since it would prevent users from just scrolling through a directory list and seeing all that's available at once, though that could be remedied by having a text file with the list that would have to be maintained... or a wiki page(s) with pictures (which would probably be more than we want)?

### Packages
I'm all for a readme; speaking of which... should we do a wiki or have all the explanations in the Readme.md?

We should ask a few people in the office who aren't CS majors if they feel that "packages" is explanatory instead of theorizing probably lol

### Readme
Yeah readme is still very rough draft atm :P Not sure how much we want in the readme as verses a wiki... I feel like if we're doing in-depth walk-through it's better to have a wiki.

I think having people put readmes in their directories is a good idea; lets users know what a style does or is supposed to look like before they install.

### Files

My GUI is terrible and I feel bad.  I'll fix later.

**Comment by cascadeth** [comment]
Ooooooo preview images in the wiki.  Best. Idea. Ever.

Anyone and everyone that has a style to submit or currently has one must create a wiki page for it that contains info about the style, as well as preview images.

**Comment by ginafish** [comment]
Renamed back to Packages as well (do we want to do maybe _Packages so it shows at the top and is separatish from the program-specific folder entries?).

**Comment by cascadeth** [comment]
Not a bad idea with the `_Packages`

**Comment by cascadeth** [comment]
Looks good woohoo!

**Pull request merged**
