### PR TITLE
Added my themes

### PR DESCRIPTION
**Pull request by ginafish**
Added my themes and readmes.  All are basically WIP, except SkinnTD.

### CODE REVIEW

**Comment by cascadeth** [comment]
Yo, your readme's say follow the MOZILLA AIO installation instructions, but there's no MOZILLA files provided... :_(

**Comment by ginafish** [comment]
They are mozilla-style CSS... lol... did the Mozilla export from Stylish.

**Comment by cascadeth** [comment]
Let's try to keep a universal naming convention.  The point of the MOZILLAs is that they're importable, and should be labeled so.  They have extra lines that make it so, but if someone by passes them thinking they're regular ole CSS, confusion occurs.

**Comment by ginafish** [comment]
No worries, I haven't had the time either lol.

Still not sure what you mean by that; isn't the Mozilla export through stylish in the Mozilla format?  It has the extra lines.  Do you mean the names of the files having "mozilla" in them?

**Comment by cascadeth** [comment]
Aha, everything is in order now.  Tis goooood.

**Pull request merged**
